{% set name = "xcube-zenodo" %}
{% set version = "0.1.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-zenodo/archive/refs/tags/v0.1.1.tar.gz
  sha256: d928f974daa730056b0370ac1fb855dd1b0c82c2aab82b7c7acdba2fd6292ce5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsspec
    - numpy
    - requests
    - xarray
    - xcube >=1.8.1
    - zarr >=2.11,<3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xcube_zenodo
  commands:
    - pip check

about:
  summary: xcube-zenodo is a xcube data store to open data resource published on zenodo.org.
  home: https://github.com/xcube-dev/xcube-zenodo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-zenodo is a Python package
  dev_url: https://github.com/xcube-dev/xcube-zenodo

extra:
  recipe-maintainers:
    - konstntokas
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
    - b-yogesh
