{% set name = "xcube-zenodo" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-zenodo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f13c0fef74c4cb964175a50896ccb71322f86ed7a67428f417f360ca8bb86554

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsspec
    - numpy
    - requests
    - xarray
    - xcube >=1.9.0
    - zarr >=2.11,<3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xcube_zenodo
  commands:
    - pip check

about:
  summary: xcube-zenodo is a xcube data store to open data resource published on zenodo.org.
  home: https://github.com/xcube-dev/xcube-zenodo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-zenodo is a Python package
  dev_url: https://github.com/xcube-dev/xcube-zenodo

extra:
  recipe-maintainers:
    - konstntokas
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
    - b-yogesh
