{% set name = "xcube-zenodo" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-zenodo/archive/refs/tags/v0.1.0.tar.gz
  sha256: 205008d464ae1506853218e034ab9ce213a07c6ce3cc3e4f7975f29fe5bbe9f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsspec
    - numpy
    - requests
    - tabulate
    - xarray >=2022.6, <=2024.6
    - xcube >=1.7.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xcube_zenodo
  commands:
    - pip check

about:
  summary: xcube-zenodo is a xcube data store to open data resource published on zenodo.org.
  home: https://github.com/xcube-dev/xcube-zenodo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-zenodo is a Python package
  dev_url: https://github.com/xcube-dev/xcube-zenodo

extra:
  recipe-maintainers:
    - konstntokas
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
    - b-yogesh
