{% set name = "xcube-zenodo" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-zenodo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 57aca999cdfb7623eb83bac398990e5976ac2a719d69e47c93fecce17d030457

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fsspec
    - numpy
    - rarfile
    - requests
    - xarray
    - xcube >=1.13.1
    - zarr >=2.11,<3

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xcube_zenodo
  commands:
    - pip check

about:
  summary: xcube-zenodo is a xcube data store to open data resource published on zenodo.org.
  home: https://github.com/xcube-dev/xcube-zenodo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-zenodo is a Python package
  dev_url: https://github.com/xcube-dev/xcube-zenodo

extra:
  recipe-maintainers:
    - TonioF
    - forman
    - pont-us
    - konstntokas
    - AliceBalfanz
    - thomasstorm
    - TejasMorbagal
    - b-yogesh
